config/routes.rb
TripPlanner::Application.routes.draw do
  get "trips/new"

  authenticated :user do
    root :to => 'trips#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :trips
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :destination, 
                  :description,
                  :enddate, 
                  :purpose, 
                  :startdate, 
                  :title,
                  :picture

  has_attached_file :picture, { :styles => { :large => "400 x 300", :medium => "300 x 240", :thumb => "200 x 140"}, :default_url => "/images/:style/missing.png" }              

  belongs_to :user

  default_scope -> { order('created_at DESC') }
  validates :description, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, 
          :registerable,
          :recoverable, 
          :rememberable, 
          :trackable, 
          :validatable,
          :token_authenticatable,
          :omniauthable

  attr_accessible :role_ids, :as => :admin       
  
  attr_accessible :avatar, 
                  :firstname,
                  :lastname, 
                  :username,
                  :gender, 
                  :email, 
                  :password, 
                  :password_confirmation, 
                  :remember_me
  
  has_attached_file :avatar, { :styles => {:medium => "300 x 240", :thumb => "112x112#", :mini => '44x44#'}, :default_url => "/images/:style/missing.png" }

  #validates_presence_of :firstname, :lastname
  validates_uniqueness_of :email, :case_sensitive => false

  has_many :groups
  has_many :trips, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_filter :authenticate_user!

  def index
    #@user = User.find(params[:user])
    #@trips = @user.trips.paginate(page: params[:page])
    @trips = current_user.trips.paginate(page: params[:page])
  end

  def show
    @trip = Trip.find(params[:id]) 
  end

  def new
    @trip = Trip.new(params[:trip])
  end

  def create
    @trip = current_user.trips.build(params[:trip])
    if @trip.save
      flash[:sucess]= "New Trip created"
      redirect_to trips_path
    else
      render root_url
    end
  end

  def destroy
    
  end

  def edit
    @trip = Trip.find(params[:id])  
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update_attributes(params[:trip])
      flash[:sucess] = "Profile Updated"
      redirect_to @trip
    else
      render 'edit'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @trips = @user.trips.paginate(page: params[:page])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/home/index.html.erb
<h3>Home</h3>


  <% if user_signed_in?%>
  <%= link_to "Add A Trip", new_trip_path, :class => "btn btn-info" %>

  <% end %>

app/views/home/show.html.erb
<h3>Home</h3>

<%= link_to "Add A Trip", new_trip_path, :class => "btn btn-info" %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Trip Planner", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>

    <li>
      Logged in as: 
      <%= image_tag current_user.avatar.url(:mini) %>
      <%= current_user.email %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Trip Planner" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Trip Planner" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/trips/_form.html.erb
<div>
  <%= f.label :picture, "Upload your Picture"%>
  <%= f.file_field :picture %></br>
  Current Trip Pic: <%= image_tag @trip.picture.url(:thumb)%>
</div>

<div>
  <%= f.label :destination %>
  <%= f.text_field :destination %>
</div>


<div>
  <%= f.label :description %>
  <%= f.text_area :description, :size => "10x10", placeholder: "Add a description here....."%>
</div>

<div>
  <%= f.label :startdate %>
  <%= f.text_field :startdate %>
</div>

<div>
  <%= f.label :enddate %>
  <%= f.text_field :enddate %>
</div>

<div class="options">
<%= f.radio_button :purpose, 'business' %>
<%= f.label :pupose, 'business' %>
<%= f.radio_button :purpose, 'pleasure' %>
<%= f.label :purpose, 'pleasure' %>
</div>

app/views/trips/_trip.html.erb
<li>
	<p><%= link_to (image_tag trip.picture.url(:thumb)), trip %>
	<%= trip.description %>
	<%= image_tag trip.user.avatar.url(:mini) %>
	<%= trip.user.username %></p>
</li>

app/views/trips/edit.html.erb
<h2>Edit a new Trip</h2>
<div class="row">
  <div class="span6 offset3">
	<%= form_for @trip, html: { multipart: true, class: 'standard' } do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	  <%= render :partial => 'form', locals: { f: f } %>

	  <div>
	    <%= f.submit "Edit your trip" %>
	  </div>
	<% end %>
	<div>
</div>

app/views/trips/index.html.erb
<% provide(:title, 'All Trips') %>


<% if current_user.trips.any? %>

	<div id="trips">
		<%= render @trips %>
	</div>
<% end %>

<%= will_paginate %>

app/views/trips/new.html.erb
<h2>Add a new Trip</h2>
<div class="row">
  <div class="span6 offset3">
	<%= form_for @trip, html: { multipart: true, class: 'standard' } do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	  <div>
	    <%= f.label :picture, "Upload your Picture"%>
	    <%= f.file_field :picture %>
	  </div>

	  <div>
	    <%= f.label :description %>
	    <%= f.text_field :description %>
	  </div>


	  <div>
	    <%= f.label :description %>
	    <%= f.text_area :description, :size => "10x10", placeholder: "Add a description here....."%>
	  </div>

	  <div>
	    <%= f.label :startdate %>
	    <%= f.text_field :startdate %>
	  </div>

	  <div>
	    <%= f.label :enddate %>
	    <%= f.text_field :enddate %>
	  </div>

	  <div class="options">
	  <%= f.radio_button :purpose, 'business' %>
	  <%= f.label :pupose, 'business' %>
	  <%= f.radio_button :purpose, 'pleasure' %>
	  <%= f.label :purpose, 'pleasure' %>
	</div>

	  <div>
	    <%= f.submit "Submit your trip" %>
	  </div>
	<% end %>
	<div>
</div>

app/views/trips/show.html.erb
<%= link_to (image_tag @trip.picture.url(:medium)), trip_path %>

<%= link_to @trip.user do %>
	<%= @trip.user.firstname %>
<% end %>

<%= @trip.description %>

<%= link_to('Edit trip info', edit_trip_path(@trip))%>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>User_Id</th>
      <th>Avatar</th>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= image_tag user.avatar.url(:mini) %></td>
      <td><%= link_to user.username, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<p>Test for user: <%= @user.id %></p>

<% if @user.trips.any? %>
  <%= render @trips %>
  
<% end %>